server:
  port: 8080
#    servlet:
#     context-path: /



spring:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    mvc:
      static-path-pattern: /static
#      view:
#        prefix: /view
#        suffix: .html

    datasource:
        username: root
        password: x5
        url: jdbc:mysql://localhost:3306/lab_prac?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver

    mybatis:
        mapper-locations: classpath:mapping/*Mapper.xml
        type-aliases-package: org.huber.layui.entity

    freemarker:
      allow-request-override: false
      template-loader-path: classpath:/templates/
      cache: false
      charset: utf-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      request-context-attribute: request
      suffix: .html
#      prefix: classpath:/templates/

    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java

  #showSql
    logging:
        level:
        com:
        example:
        mapper : debug

